# Generated by Django 4.2.2 on 2023-07-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='effort',
            name='week',
            field=models.PositiveIntegerField(default=26),
        ),
        migrations.AlterField(
            model_name='habit',
            name='starting_week',
            field=models.PositiveIntegerField(default=26),
        ),
    ]
