# Generated by Django 4.2.2 on 2023-06-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_status_alter_task_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='color',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Black', 'Black')], default='Yellow', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objective',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='week',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
