# Generated by Django 4.2.2 on 2023-06-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_date_joined_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='user',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='objective',
        ),
        migrations.AddField(
            model_name='habit',
            name='week',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='effortlog',
            name='week',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
    ]
