# Generated by Django 4.2.2 on 2023-06-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_objective_goal_remove_objective_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='week',
            new_name='starting_week',
        ),
    ]
