# Generated by Django 4.2.2 on 2023-06-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_week_habit_starting_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AddField(
            model_name='habit',
            name='expected_effort',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
