# Generated by Django 4.2.2 on 2023-06-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_goal_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink'), ('gray', 'Gray'), ('brown', 'Brown'), ('black', 'Black')], default='indianred', max_length=50),
        ),
    ]
