# Generated by Django 4.2.2 on 2023-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='ending_week',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
