# Generated by Django 4.2.2 on 2023-06-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_effortlog_year_habit_year_alter_habit_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EffortLog',
            new_name='Effort',
        ),
    ]
