# Generated by Django 4.2.2 on 2023-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_habit_ending_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='ending_week',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
